allowBuilds:
  onnxruntime-node: true
  protobufjs: false
  sharp: false
packageExtensions:
  '@huggingface/transformers@4.2.0':
    dependencies:
      onnxruntime-common: 1.24.3
minimumReleaseAgeExclude:
  - '@sveltejs/kit@2.70.0'
